name: Full-Stack CI Pipeline

on:
  push:
    branches: [ "dev", "dev-*", "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '22'  
          cache: 'npm'
          cache-dependency-path: |
            aviocalm/backend/package-lock.json
            aviocalm/frontend/package-lock.json

      - name: Install Backend Dependencies
        working-directory: ./aviocalm/backend
        run: npm ci

      - name: Install Frontend Dependencies
        working-directory: ./aviocalm/frontend
        run: npm ci

      - name: Build Frontend Application
        working-directory: ./aviocalm/frontend
        run: npm run build